# This is a basic workflow to help you get started with Actions

name: 1min workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ping
        run: ping -c 60 localhost
